;;;; gentext-voice.el -- voice commands for generic-text
;;; Time-stamp: <2006-02-17 18:51:01 jcgs>

(provide 'gentext-voice)

(defvar vr-gentext-commands
  '(("end sentence" . generic-text-end-sentence)
    ("end question" . generic-text-end-question)
    ("end exclamation" . generic-text-end-exclamation)
    ("end whatever" . generic-text-end-whatever)
    ("paragraph" . generic-text-paragraph)
    ("new item" . generic-text-insert-item)
    ("ordered list" . generic-text-ordered-list)
    ("unordered list" . generic-text-unordered-list)
    ("definition list" . generic-text-definition-list)
    ("table row" . generic-text-table-row)
    ("table data" . generic-text-table-data)
    ("table heading" . generic-text-table-heading)
    ("hyperlink" . generic-text-hyperlink)
    ("citation" . generic-text-citation)
    ("header 1" . generic-text-header-1)
    ("chapter" . generic-text-header-1)
    ("header 2" . generic-text-header-2)
    ("section" . generic-text-header-2)
    ("header 3" . generic-text-header-3)
    ("subsection" . generic-text-header-3)
    ("header 4" . generic-text-header-4)
    ("subsubsection" . generic-text-header-4)
    ("horizontal rule" . generic-text-horizontal-line)
    ("image" . generic-text-image)
    ("target" . generic-text-link-target)
    ("italic style" . generic-text-italic)
    ("bold style" . generic-text-bold)
    ("emphatic style" . generic-text-emphasized)
    ("definition style" . generic-text-definition)
    ("code style" . generic-text-code)
    ("preformatted style" . generic-text-preformatted)
    ("block quote style" . generic-text-blockquote)
    ("sample style" . generic-text-sample-style)
    ("variable style" . generic-text-variable)
    ("keyboard style" . generic-text-keyboard)
    ("braces" . generic-text-braces)
    ("environment" . generic-text-environment)
    ))

;;; end of gentext-voice.el
