;;;; texinfo-voice.el --  voice commands for texinfo-mode
;;; Time-stamp: <2006-07-29 18:27:25 jcgs>

(provide 'texinfo-voice)

;; todo: replace as many of these as possible by their generic-text equivalents
(setq vr-texinfo-commands '(
 ("update every node" . texinfo-every-node-update)
 ("insert email" . texinfo-insert-@email)
 ("find environment start" . Texinfo-find-env-start)
 ("insert environment" . Texinfo-insert-environment)
 ("multiple files update" . texinfo-multiple-files-update)
 ("insert sample" . texinfo-insert-samp)
 ("insert variable" . texinfo-insert-var)
 ("insert braces" . texinfo-insert-braces)
 ("insert url" . texinfo-insert-url)
 ("tex view" . texinfo-tex-view)
 ("insert code" . texinfo-insert-code)
 ("update node" . texinfo-update-node)
 ("insert node lines" . texinfo-insert-node-lines)
 ("insert noindent" . texinfo-insert-noindent)
 ("insert definition" . texinfo-insert-dfn)
 ("insert example" . texinfo-insert-example)
 ("insert uref" . texinfo-insert-uref)
 ("insert item" . texinfo-insert-item)
 ("insert end" . texinfo-insert-end)
 ("mode menu" . texinfo-mode-menu)
 ("indent menu description" . texinfo-indent-menu-description)
 ("texindex" . texinfo-texindex)
 ("format buffer" . texinfo-format-buffer)
 ("start menu description" . texinfo-start-menu-description)
 ("show structure" . texinfo-show-structure)
 ("all menus update" . texinfo-all-menus-update)
 ("find environment end" . Texinfo-find-env-end)
 ("insert keyboard" . texinfo-insert-kbd)
 ("format region" . texinfo-format-region)
 ("tex buffer" . texinfo-tex-buffer)
 ("insert table" . texinfo-insert-table)
 ("delete from print queue" . texinfo-delete-from-print-queue)
 ("insert strong" . texinfo-insert-strong)
 ("insert quote" . texinfo-insert-quote)
 ("tex region" . texinfo-tex-region)
 ("tex print" . texinfo-tex-print)
 ("sequential node update" . texinfo-sequential-node-update)
 ("insert quotation" . texinfo-insert-quotation)
 ("master menu" . texinfo-master-menu)
 ("insert emphasis" . texinfo-insert-emph)
 ("quit job" . texinfo-quit-job)
 ("insert node" . texinfo-insert-node)
 ("make menu" . texinfo-make-menu)
 ("preview info" . preview-info-from-file)
;; ("insert block" . texinfo-insert-block)
;; ("mode _ new paragraph" . texinfo-mode-_-new-paragraph)
))

(defun preview-info-from-file ()
  "Preview a info file."
  (interactive)
  (require 'texinfmt)
  (when (file-exists-p (expand-file-name "dir"))
    (add-infodir default-directory))
  (if (save-excursion (goto-char (point-min))
		      (looking-at "Info file:"))
      (info (buffer-file-name))
    (texinfo-master-menu t)
    (basic-save-buffer)
    (save-excursion
      (goto-char (point-min))
      (or (search-forward "@setfilename" nil t)
	  (error "Texinfo file needs an `@setfilename FILENAME' line"))
      (let* ((texinfo-command-end (point))
	     (outfile (texinfo-parse-line-arg))
	     (outbuf (find-buffer-visiting outfile)))
	(message "outfile is %S, outbuf is %S" outfile outbuf)
	(when outbuf
	  (kill-buffer outbuf))))
    (texinfo-format-buffer)
    (basic-save-buffer)
    (info (buffer-file-name))))

;;; end of texinfo-voice.el
