
(defun raspberry-pi-pinout-diagram ()
  "Make a blank pinout diagram."
  (interactive)
  (let ((row-divider "  |-+-+-+-+-+-|\n"))
    (insert row-divider)
    (insert "  | inboard | | | | | edge |\n")
    (insert row-divider)
    (dotimes (i 20)
      (let* ((base (* 2 i))
	     (left (+ base 1))
	     (right (+ base 2)))
	(insert (format "  |  | %s | %d | %d | %s |  |\n"
			(cdr (assoc left raspberry-pi-pinout-alist)) left
			right (cdr (assoc right raspberry-pi-pinout-alist)))
		row-divider)))
    (search-backward " 1 ")
    (org-table-previous-field)))

(defvar raspberry-pi-pinout-alist
  '((1 . "3.3 PWR")
    (2 . "5V PWR")
    (3 . "GPIO 2")
    (4 . "5V PWR")
    (5 . "GPIO 3")
    (6 . "GND")
    (7 . "GPIO 4")
    (8 . "UART0 TX")
    (9 . "GND")
    (10 . "UART0 RX ")
    (11 . "GPIO 17")
    (12 . "GPIO 18")
    (13 . "GPIO 22")
    (14 . "GND")
    (15 . "GPIO 22")
    (16 . "GPIO 23")
    (17 . "3.3V PWR ")
    (18 . "GPIO 24")
    (19 . "GPIO 10/SPI0 MOSI")
    (20 . "GND")
    (21 . "GPIO 9/SPI0 MISO")
    (22 . "GPIO 25")
    (23 . "GPIO 11/SPI0 SCLK")
    (24 . "GPIO 8/SPI0 CSO")
    (25 . "GND")
    (26 . "GPIO 7/SPI0 CSI")
    (27 . "Reserved")
    (28 . "Reserved")
    (29 . "GPIO 5/PWM")
    (30 . "GND")
    (31 . "GPIO 6")
    (32 . "GPIO 12")
    (33 . "GPIO 13")
    (34 . "GND")
    (35 . "GPIO 19/SPI1 MISO")
    (36 . "GPIO 16/SPI1 CSO")
    (37 . "GPIO 19/SPI1 MISO")
    (38 . "GPIO 20/SPI1 MOSI")
    (39 . "GND")
    (40 . "SPI21/SPI1 SCLK"))
  "List of the pin descriptions for the pi GPIO pins.")
